version: '3.6'
services:
  api:
    image: judge0/api:latest
    volumes:
      - ./judge0-api.conf:/usr/src/api/judge0-api.conf
      - ./srv/documents:/usr/src/api/data/documents
    ports:
      - "3000:3000"
    privileged: true
    restart: always

  workers:
    image: judge0/api:latest
    command: bash scripts/workers
    volumes:
      - ./judge0-api.conf:/usr/src/api/judge0-api.conf
      - ./srv/documents:/usr/src/api/data/documents
    privileged: true
    restart: always

  db:
    image: postgres:10.3
    env_file: judge0-api.conf
    volumes:
      - ./srv/postgres-data:/var/lib/postgresql/data/
    restart: always

  redis:
    image: redis:3.2.11
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0-api.conf
    volumes:
      - ./srv/redis-data:/data
    restart: always
