default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'].presence || 'localhost' %>
  database: <%= ENV['POSTGRES_DB'].presence || 'postgres' %>
  username: <%= ENV['POSTGRES_USER'].presence || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
